# Generated by Django 4.2.20 on 2025-05-06 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(max_length=600)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='images/')),
                ('client', models.CharField(max_length=100)),
                ('year', models.CharField(max_length=4)),
                ('services', models.CharField(max_length=200)),
                ('project_type', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, unique=True)),
            ],
        ),
    ]
